- name: Extending The Partition
  hosts: Node
  tasks:
        - name: Extending the logical volume.
          community.general.lvol:
            vg: task_vg
            lv: task_lv
            size: 3g
            force: yes
